package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"app/graph/generated"
	"app/graph/model"
	"app/internal/models"
	"context"
	"fmt"
)

// Trades is the resolver for the trades field.
func (r *queryResolver) Trades(ctx context.Context, filter *model.BinanceTradeFilter) ([]*models.BinanceTradeData, error) {
	repo := r.Resolver.MongoClient.BinanceTradeRepo

	if r.Resolver.MongoClient == nil || repo == nil {
		r.Logger.Info("BincandeTradeRepo not initialized or MongoClient is nil")

		return nil, fmt.Errorf("error in queryResolver's fields")
	}

	binanceFilter := mapBinanceFilter(filter)

	trades, err := repo.Find(ctx, binanceFilter)
	if err != nil {
		return nil, err
	}

	result := make([]*models.BinanceTradeData, len(trades))

	for i := range trades {
		result[i] = &trades[i]
	}

	return result, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, filter *model.NotificationFilter) ([]*models.NotificationData, error) {
	repo := r.Resolver.MongoClient.NotificationRepo

	if r.Resolver.MongoClient == nil || repo == nil {
		r.Logger.Info("NotificationRepo not initialized or MongoClient is nil")

		return nil, fmt.Errorf("error in queryResolver's fields")
	}

	notificationFilter := mapNotificationFilter(filter)

	notifications, err := repo.Find(ctx, notificationFilter)
	if err != nil {
		return nil, err
	}

	result := make([]*models.NotificationData, len(notifications))

	for i := range notifications {
		result[i] = &notifications[i]
	}

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
