// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type BinanceTradeFilter struct {
	ID           *string             `json:"ID,omitempty"`
	Stream       *string             `json:"Stream,omitempty"`
	EventType    *string             `json:"EventType,omitempty"`
	AggregateID  *int64              `json:"AggregateID,omitempty"`
	Symbol       *string             `json:"Symbol,omitempty"`
	FirstTradeID *int64              `json:"FirstTradeID,omitempty"`
	LastTradeID  *int64              `json:"LastTradeID,omitempty"`
	IsBuyerMaker *bool               `json:"IsBuyerMaker,omitempty"`
	Price        *NumericFilterInput `json:"Price,omitempty"`
	Quantity     *NumericFilterInput `json:"Quantity,omitempty"`
	EventTime    *TimeFilterInput    `json:"EventTime,omitempty"`
	TradeTime    *TimeFilterInput    `json:"TradeTime,omitempty"`
	Regex        *string             `json:"Regex,omitempty"`
	Limit        *int64              `json:"Limit,omitempty"`
	SortField1   *string             `json:"SortField1,omitempty"`
	SortDir1     *SortDirection      `json:"SortDir1,omitempty"`
	SortField2   *string             `json:"SortField2,omitempty"`
	SortDir2     *SortDirection      `json:"SortDir2,omitempty"`
}

type NotificationFilter struct {
	EventTime    *string             `json:"EventTime,omitempty"`
	Symbol       *string             `json:"Symbol,omitempty"`
	IsBuyerMaker *bool               `json:"IsBuyerMaker,omitempty"`
	Price        *NumericFilterInput `json:"Price,omitempty"`
	Quantity     *NumericFilterInput `json:"Quantity,omitempty"`
	TotalPrice   *NumericFilterInput `json:"TotalPrice,omitempty"`
	Regex        *string             `json:"Regex,omitempty"`
	Limit        *int64              `json:"Limit,omitempty"`
	SortField1   *string             `json:"SortField1,omitempty"`
	SortDir1     *SortDirection      `json:"SortDir1,omitempty"`
	SortField2   *string             `json:"SortField2,omitempty"`
	SortDir2     *SortDirection      `json:"SortDir2,omitempty"`
}

type NumericFilterInput struct {
	Eq  *float64 `json:"eq,omitempty"`
	Ne  *float64 `json:"ne,omitempty"`
	Gt  *float64 `json:"gt,omitempty"`
	Gte *float64 `json:"gte,omitempty"`
	Lt  *float64 `json:"lt,omitempty"`
	Lte *float64 `json:"lte,omitempty"`
}

type Query struct {
}

type TimeFilterInput struct {
	After  *time.Time `json:"after,omitempty"`
	Before *time.Time `json:"before,omitempty"`
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
